server {
    listen 80;
    server_name localhost;
    charset utf-8;
    index index.php;
    root /app/;
    access_log /var/log/nginx/php_2_access.log;
    error_log /var/log/nginx/php_2_error.log;

    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Credentials' 'true' always;
    add_header 'Access-Control-Allow-Methods' 'GET,POST,PUT,DELETE,HEAD,OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'Origin,Content-Type,Accept,Authorization,X-Features' always;

    location / {
        #try_files $uri $uri/ /index.php?args;
        try_files $uri $uri/ $uri.php;
        index index.php;

    }

    #location /templates {
     #   try_files $uri $uri/ /index.php?args;
    #}


    location /health {
        add_header Content-Type text/plain;
        return 200 'alive';
    }

    location ~ \.php$ {
        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_read_timeout 300;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
