<?php


namespace UnitTests;

require_once __DIR__ . '/../autoload.php';


use Models\Article;
use PHPUnit\Framework\TestCase;

class ArticleTest extends TestCase
{
    private Article $article;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->article = new Article();
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testFillArticle(): void
    {
        $this->article->fill(['title' => 'Заголовок', 'content' => 'Содержимое']);
        $this->assertEquals('Заголовок', $this->article->title);
        $this->assertEquals('Содержимое', $this->article->content);
    }

    public function testAddArticleShortTitle(): void
    {

        try {
            $this->article->validateTitle('ff');
        } catch (\Exception $e) {
            $this->assertEquals('Length of the title is not compatible!', $e->getMessage());
            return;
        }
        $this->fail('Expected exception for short title');
    }


    public function testAddArticleShortContent(): void
    {
        $this->expectException(\Exception::class);
        $this->article->validateContent('ddff');
    }

}